In [ ]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

## Dynamic Programming Refresher
### Reinforcement Learning
<p style="color:blue;">
By Pramod Sharma : pramod.sharma@prasami.com
<p>
Dated : 07-Sep-2018

In [ ]:
## Import Statements
import sys
import os
import numpy as np
import matplotlib.pyplot as plt
import random
import unittest

In [ ]:
# Setup inline display and other matplotlib parameters
# Some basic parameters
inpDir = '../input'
outDir = '../output'

RANDOM_STATE = 24
STEPS = 200

# parameters for Matplotlib
params = {'legend.fontsize': 'x-large',
          'figure.figsize': (9, 6),
          'axes.labelsize': 'x-large',
          'axes.titlesize':'x-large',
          'xtick.labelsize':'x-large',
          'ytick.labelsize':'x-large'
         }

plt.rcParams.update(params)

## 1. Tree and Graphs

Tree and graph problems are some of the trickiest. Searching a tree is more complicated than searching in a linearly organized data structure such as an array or linked list. Additionally, the worst case and average case time may vary wildly, and we must evaluate both aspects of any
algorithm.

For getting a good handle in RL, fluency in implementing a tree or graph from scratch will prove essential.

Because most people are more familiar with trees than graphs (and they're a bit simpler), we'll discuss trees
first. This is a bit out of order though, as a tree is actually a type of graph.</p>


### 1.1 Types of Trees
A nice way to understand a tree is with a recursive explanation. 
- A tree is a data structure composed of nodes.
- Each tree has a root node. 
- The root node has zero or more child nodes.  
- Each child node has zero or more child nodes, and so on.
- The tree cannot contain cycles.
- The nodes may or may not be in a particular order, they could have any data type as values, and they may or may not have links back to their parent nodes.


### 1.2 Trees vs. Binary Trees
A binary tree is a tree in which each node has up to two children. Not all trees are binary trees. For example,
this tree is not a binary tree. You could call it a ternary tree.

<img src='./images/binary_tree.png' alt='Tree' style='width: 600px;'>

### Binary Tree vs. Binary Search Tree
A binary search tree is a binary tree in which every node fits a specific ordering property:<br>
`all left descendents <= n < all right descendents`<br> This must be true for each node n.

### Balanced vs. Unbalanced
While many trees are balanced, not all are. Note that balancing a tree does not mean the left and right subtrees are exactly the same size (like you see under "perfect binary trees" in the diagram above).

<img src='./images/binary_tree_2.png' style='width:800px;'>

## In-Order Traversal
In-order traversal means to "visit" (often, print) the left branch, then the current node, and finally, the right
branch. When performed on a binary search tree, it visits the nodes in ascending order (hence the name "in-order").
## Pre-Order Traversal
Pre-order traversal visits the current node before its child nodes (hence the name "pre-order"). In a pre-order traversal, the root is always the first node visited.
## Post-Order Traversal
Post-order traversal visits the current node after its child nodes (hence the name "post-order"). In a post-order traversal, the root is always the last node visited.

In [ ]:
class Node(object):
    
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None
        
class BinaryTree(object):
    
    def __init__(self, root):
        self.root = Node(root)
        
    def fn_print_tree(self, traverse_type):
        
        if traverse_type == 'preorder':
            return print (self.fn_preorder_traverse(tree.root, ''))
       
        elif traverse_type == 'inorder':
            return print (self.fn_inorder_traverse(tree.root, ''))
        
        elif traverse_type == 'postorder':
            return print (self.fn_postorder_traverse(tree.root, ''))
        
        else:
            print ('traverse type not supported')
        
    def fn_preorder_traverse(self, start, traverse):
        if start:
            traverse += ('{}-'.format(start.value))
            traverse = self.fn_preorder_traverse(start.left, traverse)
            traverse = self.fn_preorder_traverse(start.right, traverse)
        return traverse
    
    def fn_inorder_traverse(self, start, traverse):
        if start:
            traverse = self.fn_inorder_traverse(start.left, traverse)
            traverse += ('{}-'.format(start.value))
            traverse = self.fn_inorder_traverse(start.right, traverse)
        return traverse
    
    def fn_postorder_traverse(self, start, traverse):
        if start:
            traverse = self.fn_postorder_traverse(start.left, traverse)
            traverse = self.fn_postorder_traverse(start.right, traverse)
            traverse += ('{}-'.format(start.value))
        return traverse

<img src='./images/binary_tree_4.png' style='width:600px;'>

In [ ]:
tree = BinaryTree('A')

tree.root.left = Node('B')
tree.root.right = Node('C')

tree.root.left.left = Node('D')
tree.root.left.right = Node('E')

tree.root.left.left.left = Node('F')
tree.root.left.left.right = Node('G')

tree.root.right.left = Node('H')
tree.root.right.right = Node('I')

print ('PreOrder: ', end = ' ')
tree.fn_print_tree('preorder')

print ('InOrder : ', end = ' ')
tree.fn_print_tree('inorder')

print ('Postorder : ', end = ' ')
tree.fn_print_tree('postorder')

PreOrder:  A-B-D-F-G-E-C-H-I-
InOrder :  F-D-G-B-E-A-H-C-I-
Postorder :  F-G-D-E-B-H-I-C-A-


### Demo 1.1 Route Between Nodes: 
Given a directed graph, design an algorithm to find out whether there is a route between two nodes.

**Design:**
- class Node:
     - Attributes: 
         - name,
         - adjacent_nodes,
         - shortest_path
    - Methods:
        - add_edge
        - set_short_path
- class Queue
    - Attributes: 
         - array : containing the list of nodes
    - Methods:
        - put_item
        - get_item

**Algo:**
1. select start node
2. iterate over adjacent nodes
3. add nodes's short path to adjacent nodes
4. add adjecent nodes to queue
5. add adjecent nodes to visited nodes (a local list)

In [ ]:
class Node (object):
    
    def __init__(self, name, adjacent_nodes = None):
        
        self.name = name 
        self.adjacent_nodes = adjacent_nodes or []
        self.short_path = None
    
    def add_edge(self, node):
        if isinstance(node, Node):
            self.adjacent_nodes.append(node)
    
    def __str__(self):
        return '{}'.format(self.name)
    
    __repr__ = __str__

In [ ]:
# Helper Functions
#convert path to string
def to_string(path):

    if path is not None:
        nd_nms = [x.name for x in path]
        return('->'.join(nd_nms))
    else:
        return 'None'

In [ ]:
def find_route(node1, node2):
    
    if isinstance(node1, Node) and isinstance(node2, Node): # verify if both inputs are node
        found_path = None # define found path variable
        q = Queue() # Create a Queue object
        v_nds = []  # this is list of visited nodes
        curr = node1 # input node is defined as current node
        curr.short_path = [curr] # append current node to 'short_path'
        node2.short_path = None
        v_nds = [curr]
        
        while curr:
            
            #print ('Current Node:', curr, 'Short_path:', to_string(curr.short_path))
            #print ('Queue:', q)
            
            for adj in curr.adjacent_nodes:
                
                #print ('Adj Node:', adj, end = ' ')

                if not adj.short_path:

                    adj.short_path = curr.short_path + [adj] # add current nodes shortest path to adjacent node

                    if adj == node2:
                        found_path = curr.short_path + [adj]
                        break
                        
                    q.put_item(adj)
                    
                    v_nds.append(adj)
                
                print ('Path:', to_string(adj.short_path))

                    
            curr = q.get_item() # get next node from queue
            
        print ('\n Clearing :')
        
        for nd in v_nds: # make all null for future search
            print(nd.name, end =' ')
            nd.short_path = None
        print ('')
        
        return found_path
        
    else:
        print ( 'Only Node object allowed' )


class Queue ():
    
    def __init__( self ):
        self.array = []
    
    def put_item(self, node):
        self.array.append(node)
        
    def get_item(self):
        if not len(self.array):
            return None
        return self.array.pop(0)
    
    def is_empty(self):
        return len(self.array) == 0
    
    def __str__ (self):
        nd_nms = [x.name for x in self.array]
        return ','.join(nd_nms)

<img src = './images/binary_tree_3.png' style='width:600px;'>

In [ ]:
# Test Harness

class Test(unittest.TestCase):
    
    def test_find_route(self):
        node_j = Node('J')
        node_i = Node('I')
        node_h = Node('H')
        node_d = Node('D')
        node_f = Node('F', [node_i])
        node_b = Node('B', [node_j])
        node_g = Node('G', [node_d, node_h])
        node_c = Node('C', [node_g])
        node_a = Node('A', [node_b, node_c, node_d])
        node_e = Node('E', [node_f, node_a])
        node_d.add_edge(node_a)
        self.assertEqual(to_string(find_route(node_a, node_i)), 'None')
        self.assertEqual(to_string(find_route(node_a, node_j)), 'A->B->J')
        node_h.add_edge(node_i)
        self.assertEqual(to_string(find_route(node_a, node_i)), 'A->C->G->H->I')


if __name__ == '__main__':
    unittest.main(argv=['to be ignored'], exit=False)

.

Path: A->B
Path: A->C
Path: A->D
Path: A->B->J
Path: A->C->G
Path: A
Path: A->D
Path: A->C->G->H

 Clearing :
A B C D J G H 
Path: A->B
Path: A->C
Path: A->D
Path: A->C->G
Path: A
Path: A->D
Path: A->C->G->H

 Clearing :
A B C D G H 
Path: A->B
Path: A->C
Path: A->D
Path: A->B->J
Path: A->C->G
Path: A
Path: A->D
Path: A->C->G->H

 Clearing :
A B C D G H 



----------------------------------------------------------------------
Ran 1 test in 0.008s

OK


### Ex 1.2 Minimal Tree:
Given a sorted (increasing order) array with unique integer elements, write an algorithm to create a binary search tree with minimal height.

**Design:**
- class Node:
     - Attributes: 
         - name,
         - left,
         - right
    - Methods:
        - add_edge
        - set_short_path
- Create Tree with recursion

In [ ]:
# This function to be coded
'''
    Divide array in three parts, left array, right array and middle value
    Call the recursively and return Node with values as Middle, left_array, right_array
'''
def create_Tree(array):
    
    #Base condition : Think of minimum valid input
    if len(array) == 1:
        return Node(array[0],None, None )
    
    elif len(array) ==2:
        return Node(array[1],array[0],None)
    
    else:
        # Find middle value
        middle = int(len(array)/2)

        # Create Left Array
        left_array = array[:middle]
        left_array = create_Tree(left_array)

        # Create right array
        right_array = array[middle+1:]
        right_array = create_Tree(right_array)

        # Return node constructed from above
        return Node(array[middle],left_array, right_array)

# Node Class    
class Node (object):
    
    def __init__(self, data, left, right):
        self.data = data
        self.left = left
        self.right = right
    
    def __str__(self):
        return '{}'.format(self.data)
    
    __repr__ = __str__

In [ ]:
# Test Harness

class Test(unittest.TestCase):
    array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
    node = create_Tree(array)
    
    def test_left(self):
        self.assertEqual(self.node.data, 7)
        self.assertEqual(self.node.left.data, 4)
        self.assertEqual(self.node.left.left.data, 2)
        self.assertEqual(self.node.left.left.left.data, 1)
        
    def test_right(self):
        self.assertEqual(self.node.data, 7)
        self.assertEqual(self.node.right.data, 10)
        self.assertEqual(self.node.right.right.data, 12)
        
if __name__ == '__main__':
    unittest.main(argv=['to be ignored'], exit=False)

..
----------------------------------------------------------------------
Ran 2 tests in 0.002s

OK


### Ex 1.3 Check Subtree: 
Tl and T2 are two very large binary trees, with Tl much bigger than T2. Create an algorithm to determine if T2 is a subtree of Tl. A tree T2 is a subtree of Tl if there exists a node n in Tl such that the subtree of n is identical to T2. That is, if you cut off the tree at node n, the two trees would be identical.

**Hint**:
Two condition to match for it to be a sub tree. Both pre and post orders will be a subset.

In [ ]:
class Node(object):

    def __init__(self, value, left = None, right = None):
        
        self.value  = value
        self.left   = left
        self.right  = right

    def __str__ (self):
        return '{}, [{},{}]'.format(self.value, 
                                    self.left, 
                                    self.right)
    

In [ ]:
class BST(object):
    
    def __init__ (self, root: Node):
        
        self.root = root
        self.inOrderList = []
        self.preOrderList = []
        self.postOrderList = []
    
    def insert (self, nd : Node = None):
        
        if isinstance(nd, Node):
            if self.root is None:
                self.root = nd
            else:
                self._insert(nd, self.root)
    
    def _insert(self, nd: Node, curr: Node):
        
        if nd.value == curr.value:
            
            return 'Value exists'
            
        if nd.value < curr.value:
            if curr.left == None:
                curr.left = nd
            else:
                curr = curr.left
                
        if nd.value > curr.value:
            if curr.right == None:
                curr.right = nd
            else:
                curr = curr.right
        
        return self._insert(nd, curr)
    
    def in_order(self, nd):

        if nd:
            self.inOrderList.append(nd.value)
            self.in_order(nd.left)
            self.in_order(nd.right)
            return self.inOrderList
        
    def pre_order(self, nd):
        
        if nd:
            self.pre_order(nd.left)
            self.preOrderList.append(nd.value)
            self.pre_order(nd.right)
            return self.preOrderList
            
    def post_order(self, nd):

        if nd:
            self.post_order(nd.left)
            self.post_order(nd.right)
            self.postOrderList.append(nd.value)
            return self.postOrderList

    def __str__ (self):
        return str(self.root)

In [ ]:
#### Code here...

def is_subset(main,sub):
    if(all(x in main for x in sub)): 
        return True
    else:
        return False

In [ ]:
def check_sub_tree(t1, t2):
    
    #### Code here...
    #Case 1: Pre-Order
    t1_preorder = t1.pre_order(bst_t1.root)
    t2_preorder = t2.pre_order(bst_t2.root)
    #Case 2: Pre-Order
    t1_postorder = t1.post_order(bst_t1.root)
    t2_postorder = t2.post_order(bst_t2.root)
    # check if both Pre and Post are subset, then its a sub tree
    if is_subset(t1_preorder,t2_preorder) and is_subset(t1_postorder,t2_postorder) : return True
    else: return False

In [ ]:
# Lets define two trees

bst_t1 = BST(Node(16))
bst_t1.insert(Node(8))
bst_t1.insert(Node(24))
bst_t1.insert(Node(4))
bst_t1.insert(Node(12))
bst_t1.insert(Node(20))
bst_t1.insert(Node(28))
bst_t1.insert(Node(2))
bst_t1.insert(Node(6))
bst_t1.insert(Node(10))
bst_t1.insert(Node(14))
bst_t1.insert(Node(18))
bst_t1.insert(Node(22))
bst_t1.insert(Node(26))
bst_t1.insert(Node(30))
print ('Root Node :', bst_t1.root,'\n')
print ('In Order list   :', bst_t1.in_order(bst_t1.root))

print ('Pre Order list  :', bst_t1.pre_order(bst_t1.root))

print ('Post Order list :', bst_t1.post_order(bst_t1.root))

Root Node : 16, [8, [4, [2, [None,None],6, [None,None]],12, [10, [None,None],14, [None,None]]],24, [20, [18, [None,None],22, [None,None]],28, [26, [None,None],30, [None,None]]]] 

In Order list   : [16, 8, 4, 2, 6, 12, 10, 14, 24, 20, 18, 22, 28, 26, 30]
Pre Order list  : [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
Post Order list : [2, 6, 4, 10, 14, 12, 8, 18, 22, 20, 26, 30, 28, 24, 16]


In [ ]:
bst_t2 = BST(Node(24))
bst_t2.insert(Node(20))
bst_t2.insert(Node(28))
bst_t2.insert(Node(18))
bst_t2.insert(Node(22))
bst_t2.insert(Node(26))
bst_t2.insert(Node(30))

print ('Root Node :', bst_t2.root,'\n')
print ('In Order list   :', bst_t2.in_order(bst_t2.root))

print ('Pre Order list  :', bst_t2.pre_order(bst_t2.root))

print ('Post Order list :', bst_t2.post_order(bst_t2.root))

Root Node : 24, [20, [18, [None,None],22, [None,None]],28, [26, [None,None],30, [None,None]]] 

In Order list   : [24, 20, 18, 22, 28, 26, 30]
Pre Order list  : [18, 20, 22, 24, 26, 28, 30]
Post Order list : [18, 22, 20, 26, 30, 28, 24]


In [ ]:
check_sub_tree(bst_t1, bst_t2)

True

In [ ]:
# Negative test
tree1 = BST(Node(5))
tree1.insert(Node(3))
tree1.insert(Node(2))
tree1.insert(Node(4))
tree1.insert(Node(8))
tree1.insert(Node(7))
tree1.insert(Node(9))
print (tree1)

tree2 = BST(Node(8))
tree2.insert(Node(7))
tree2.insert(Node(1))
print (tree2)

tree3 = BST(Node(8))
tree3.insert(Node(7))
tree3.insert(Node(9))

5, [3, [2, [None,None],4, [None,None]],8, [7, [None,None],9, [None,None]]]
8, [7, [1, [None,None],None],None]


In [ ]:
check_sub_tree(tree1, tree2)

True

## 2 DP
### 2.1 Robot in a Grid

In [ ]:
grid = np.array([[  1,   2,   2,   2,   2,   2],
                 [  1,   0, 100,   0, 100,   2],
                 [  1, 100,   0, 100,   0,   2],
                 [  1,   1,   1,   1, 100,   2],
                 [100,   0, 100,   1,   1,   1],
                 [  0,   0,   0,   0, 100,   1]])

In [ ]:
# Minimum cost of traveling
def walk(grid, n, m):

    # Base condition
    if n == 0 and m == 0:
        return grid[0,0]
    
    if n < 0 or m < 0:
        return 10   # penalise if it goes beyond 
    else:
        #print(m,n, grid[n,m])
        return (grid[n, m] + min(walk(grid, n-1, m), walk(grid, n, m-1) ) )

In [ ]:
n, m = grid.shape
n -=1
m-=1
walk(grid, n, m)

11

In [ ]:
# Minimum cost of traveling

def min_cost(grid,n, m):
    
    # Create DP
    dp =np.full((n+1, m+1),-1)
    
    # Base condition
    dp[ 0, 0 ] = grid[0,0]
    
    for j in range (1, m + 1 ):
        dp [0,j] = grid[0,j] + dp [0,j-1] 

    for i in range (1, n + 1 ):
        dp [i,0] = grid[i,0] + dp [i-1, 0]
    
    for j in range(1, m+1):
        for i in range(1, n+1):
            dp[i,j] = grid[i,j] + min (dp [ i-1, j ], dp [ i, j-1 ] )
    
    return dp[n,m], dp

In [ ]:
n, m = grid.shape
res, dp = min_cost(grid, n-1, m-1)
print (res)

11


In [ ]:
dp

array([[  1,   3,   5,   7,   9,  11],
       [  2,   2, 102,   7, 107,  13],
       [  3, 102, 102, 107, 107,  15],
       [  4,   5,   6,   7, 107,  17],
       [104,   5, 105,   8,   9,  10],
       [104,   5,   5,   5, 105,  11]])

### 2.2 Knapsack
- wt = [ 1,5,6,8,9]
- val = [10,8,6,4,2]
- W = 11

In [ ]:
# Recursion based approach

def solve_rec(wt, val, W, n):
 
    # Base condition
    if n == 0:
        return 0
    if W == 0:
        return 0
    
    # Decision Tree
    if W < wt[n-1]:
        return solve_rec(wt, val, W, n-1) # do not keep, call with one less
    
    else:
        
        return max(val[n-1] + solve_rec(wt, val, W-wt[n-1], n-1), solve_rec(wt, val, W, n-1)) # keep or otherwise 

In [ ]:
wt = [ 1,5,6,8,9]
val = [10,8,6,4,2]
W = 11
solve_rec(wt, val, W, len(wt))

18

### 2.3 Knapsack with Memoization

In [ ]:
def knap_sack_rec(W: int, wt: list, val: list, n: int):
    #print (W, wt[n], val[n], n)
   
    
    # base condition
    if W == 0 or n == 0: # either we do not want to put
                         # any thing in the sack or there are no items
        return 0
    
    # Check if value exists
    if dp[n][W] != -1:
        return dp[n][W]

    # Decision tree
    if W >= wt[n-1]: # if remaining weight is more than the weight of item under consideration
        dp[n][W] = max(val[n-1] + knap_sack_rec(W-wt[n-1], wt, val, n-1),  # include item
                              knap_sack_rec(W, wt, val, n-1))         # no do not include item
    else:
        dp[n][W] = knap_sack_rec(W, wt, val, n-1) # can't include move over to next item
    
    return (dp[n][W])  

if __name__ == '__main__':
    wt = [ 1,5,6,8,9]
    val = [10,8,6,4,2]
    W = 11
    n = len(val)
    dp = [[-1 for _ in range(W +1)] for _ in range(n+1)]
    print(knap_sack_rec(W, wt, val, n))

18


### 2.3 Knapsack with bottomup

In [ ]:
def knap_sack_dp(W, wt, val, n):
    
    # Preparing dp matrix
    dp = [[0 for x in range(W + 1)] for x in range(n + 1)] 
    
    # Base condition
    dp[0][0] = 0

    # Build matrix dp[][] in bottom up manner 
    for i in range(1, n + 1): # loop over all elements 
        for w in range(1, W + 1):
            
            if wt[i-1] <= w:  
                dp[i][w] = max(val[i-1] + dp[i-1][w-wt[i-1]],  dp[i-1][w]) 
            
            else: 
                dp[i][w] = dp[i-1][w] 
    return dp[n][W] 
  
if __name__ == '__main__':
    wt = [ 1,5,6,8,9]
    val = [10,8,6,4,2]
    W = 11
    n = len(val) 
    print(knap_sack_dp(W, wt, val, n-1)) 

18


### 2.4 Triple Step
A child is running up a staircase with n steps and can hop either 1 step, 2 steps, or 3 steps at a time. Implement a method to count how many possible ways the child can run up the
stairs.
- array : [1,2,3]
- sum : 10

In [ ]:
# Define Problem
arr = np.array([1, 2, 3])
S = 10

In [ ]:
def climb_stairs(st, stair):
    
    n = len(st)
    m = stair
    
    # Initialise dp
    dp = np.full((n+1,m+1), -1)
    
    # base condition
    dp [ 0, :] = 0 # stairs is there but no steps
    dp [ :, 0] = 1 # there are no steps still one way to do it
    
    #dp [:, 1 ] = 1
    #dp [:, 2 ] = 2
    for j in range (1, m+1):
        
        for i in range (1, n+1):
            
            if st[i-1]<= j:
                dp[i,j] = dp[i, j - st[i-1]] + dp[i-1, j]
            
            else:
                dp[i,j] = dp[i-1, j]
    
    print (dp)
    
climb_stairs(arr, S)

[[ 1  0  0  0  0  0  0  0  0  0  0]
 [ 1  1  1  1  1  1  1  1  1  1  1]
 [ 1  1  2  2  3  3  4  4  5  5  6]
 [ 1  1  2  3  4  5  7  8 10 12 14]]


### Ex 2.2 Sudoku (Optional)
Implement 9 x 9 sudoku

### Ex 2.2 Queen Placement (Optional)
Place N queens on N x N chess board so that none of the queen is under attack.
**Hint**
We will place one queen in one columns. So we need to track their placement on an array insted of a matrix


<img src = './images/eight_queens.png' style='width:600px;'>